@startuml

participant Aplicacion
participant "nuevo:Cliente" as Cliente
participant Clave
collections "indices:Indice" as Indice

create Cliente
Aplicacion -> Cliente: crearCliente()
activate Cliente
return nuevo
Aplicacion -> Cliente: formularioCliente(nuevo)
activate Cliente
return nuevo
Aplicacion -> Clave: crearClave(nuevo, posicionArchivo)
activate Clave
return
loop por cada indice en indices
	Aplicacion -> Indice: agregarClaveIndice(Clave)
	activate Indice
	return
end

@enduml
