@startuml

participant Aplicacion
participant Cliente
participant Credito

Aplicacion -> Cliente: obtenerCreditos(cliente)
activate Cliente
return creditos
Aplicacion -> Cliente: esPosibleOtroCredito(cliente)
activate Cliente
return esPosible
opt esPosible
	create Credito
	Aplicacion -> Credito: crearCredito()
	activate Credito
	return nuevoCredito
	Aplicacion -> Credito: formularioCredito(nuevoCredito)
	activate Credito
	return nuevoCredito
	Aplicacion -> Cliente: crearCreditoCliente(nuevoCredito)
	activate Cliente
	return
end

@enduml
