@startuml

package tp2 <<Folder>> {
    class Aplicacion
    class Indice
    class Cliente
    class Credito
    class Iterador
}

package stdio.h <<Folder>> {
    class FILE
}

package avl.h <<Folder>> {
    class AVL
}

package menu.h <<Folder>> {
    class Menu
}

Aplicacion .left.> Menu
Aplicacion ..> Indice
Aplicacion ..> FILE
Aplicacion ..> Cliente
Aplicacion ..> Credito
Cliente -left-o Credito
Cliente ..> FILE
Indice ..> FILE
Indice *-down- AVL
Indice .up.> Iterador
Aplicacion .left.> Iterador

hide class circle

@enduml
