@startuml

participant Aplicacion
participant "vista:Indice" as Vista
participant "iterador:Iterador" as Iterador
participant "clave:Clave" as Clave
participant "cliente:Cliente" as Cliente
database "base:FILE" as FILE

activate Aplicacion
Aplicacion -> Vista: obtenerIterador()
activate Vista
return iterador
loop hasta iterador == NULL
	Aplicacion -> Iterador: siguienteIterador()
	activate Iterador
	return clave
	Aplicacion -> Clave: obtenterPosicionArchivo()
	activate Clave
	return posicionArchivo
    Aplicacion -> FILE: fseek(posicionArchivo)
    activate FILE
    return exito?
    create Cliente
    Aplicacion -> Cliente: recuperarCliente(base)
    activate Cliente
    Cliente -> FILE: fread()
    activate FILE
    return cantidadLeidos
    return cliente
    Aplicacion -> Cliente: mostrarCliente(cliente)
    activate Cliente
    return
    Aplicacion -> Cliente: borrarCliente(cliente)
    destroy Cliente
nd
deactivate Aplicacion

@enduml
