@startuml

participant Aplicacion
participant Cliente
collections "credito:Creditos" as Array

Aplicacion -> Cliente: mostrarCliente(cliente)
activate Cliente
return
Aplicacion -> Cliente: obtenerCreditos(cliente)
activate Cliente
return Creditos
loop maxint = MAX_CREDITOS
	Aplicacion -> Array: mostrarCredito(credito)
	activate Array
	return
end

@enduml
